### ISSUE TITLE
Missing getting started doc

### ISSUE THREAD

**Issue by postb99** [survirtual/vue-adal#4]
Hi,

Well, I got a working App.vue after some time spent, this is a good starting point. Thanks for the npm package!

https://gist.github.com/postb99/d5a107d67dd2b126741e09accbf5f7c9

**Comment by survirtual** [comment]
Looks good -- thanks!  The example you shared is pretty much how I do it too; though I actually use a computed property as a mixin for my application.  Here's an example:

```javascript
Vue.mixin({
  data () {
    return {
      authenticated: false
    }
  },

  computed: {
    isAuthenticated () {
      this.authenticated = this.$adal.isAuthenticated()
      return this.authenticated
    }
  }
})
```

Then, in my top-level of the vue app (App.vue usually), I do the following:

```javascript
  mounted () {
    if (!this.isAuthenticated) {
      // Show loading / checking auth popup
      setTimeout(() => {
        this.checkAuthState()
      }, 1000)
    }
  },
  methods: {
    checkAuthState () {
      if (this.$adal.isAuthenticated()) {
        this.authenticated = true
        // Hide loading / checking auth popup
      } else {
        setTimeout(() => {
          this.checkAuthState()
        }, 1000)
      }
    }
  }
```

Keep in mind, this is a tad hacky for an internal tool requiring authentication at all times, so it works for that purpose.

I'm intending to utilize Vuex for centralized state management around auth at some point in the future, which would eliminate the need for manually taking a look at the state & computed properties, since the store will handle view / state sync.
